
export const FETCH_MOVIES = 'MOVIECARD/FETCH_MOVIES';
export const FETCH_MOVIES_FAILED = 'MOVIECARD/FETCH_MOVIES_FAILED';
export const FILTER_MOVIES = 'MOVIECARD/FILTER_MOVIES';
export const SORT_MOVIES = 'MOVIECARD/SORT_MOVIES';
export const SELECT_MOVIE = 'MOVIECARD/SELECT_MOVIE';